export const ADD_MANY_ALBUMS = "ADD_MANY_ALBUMS";
export const ADD_MANY_PHOTOS = "ADD_MANY_PHOTOS";
export const ADD_ONE_ALBUM = "ADD_ONE_ALBUM";
export const ADD_ONE_PHOTO = "ADD_ONE_PHOTO";
export const GET_USER_INFO = "GET_USER_INFO";
export const ADD_ALL_USER = "ADD_ALL_USER";
export const ADD_ACTIVE_USER = "ADD_ACTIVE_USER";
export const DELETE_ACTIVE_USER = "ADD_ACTIVE_USER";
